language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
install:
- pip install -U setuptools
- pip install tox-travis
- if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip install "virtualenv<14.0.0"; fi
script:
- export CURRENT_BRANCH=$(if [ -n "$TRAVIS_TAG" ]; then echo "master"; else echo "$TRAVIS_BRANCH"; fi)
- tox
after_success: python setup.py sdist bdist_wheel
deploy:
  provider: releases
  api_key:
    secure: KbFYfqaLlzNnJnjULvAC2Uzdy1kiA9CZGvZa6uRVb5QLMl4kQoTmHdEU6UqVR6zKXt+GhViYpJAPeQI2yaxmEvrZrHxuRIaaN4jlNp3bp10x+kcuURSveDGASGIkn3pbhUpRxL0UzIYYr9My8Uex7U+YNC0a3qhTCt6N75YBdlnEQUh5Y92Houo+g2+US05+7kEvcmX0in84k2h2x19GWHb+zW8+gZ88fT3PbohehXrjfhdarj1S17O9A/jUGImZpVgd0onNASZnFUxeRzOfeldqvuHvqO1hEfdcwWRjUjBQE/JTLBFP5wNYTMspEiRV+xmBwGPTh4jg1KpuPtyBkCYNoM2Gh3HS9MLkVfsV9XZFj5ofll1WoerpQ/GginT1CJNVxBEXDDSqNoN0f7KYkyCulQC/o/EuR88MWLZttEO7iLBOlkkar7CsvFOJFxMxF2JvogC8cLHDqdtYZUE64BOB9FbjjqUh3qr8qqmvUtf4+rwLQDAbwqN2k9VYSF3kf6DZKC8y+fFBFJl4cKlxxbAUyZN+jrvVPZUybaUrtYzmDqEpAjWEZcyzVVMKZV+rEnCW5zOY6cE/4q4gI/C3Xhflx9uMssH4IWyIRazQ4IWHS3iWu7kqcPGn8IbkcgnRH2c+a5UvAArVse5oGYGXQbzQD5Y64gFyH24H/Z1CTyE=
  skip_cleanup: true
  file_glob: true
  file:
  - "dist/oem-database-updater-anidb-*"
  - "dist/oem_database_updater_anidb-*"
  on:
    repo: KingJ/oem-database-updater-anidb
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
    tags: true
