language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
install:
- pip install -U setuptools
- pip install tox-travis
- if [[ $TRAVIS_PYTHON_VERSION == 3.2 ]]; then pip install "virtualenv<14.0.0"; fi
script:
- export CURRENT_BRANCH=$(if [ -n "$TRAVIS_TAG" ]; then echo "master"; else echo "$TRAVIS_BRANCH"; fi)
- tox
after_success: python setup.py sdist bdist_wheel
deploy:
  provider: releases
  api_key:
    secure: YgRU3VcVZiBnDAffyhvEgbcqxt8n5OMm1R82U/lA0XHhguyQ7NeZ7gq5PfXu0hAfMiv7mPBHBpaw/zLobZu/NISaE+ncOj6XerfAzBEZKuKXig7VAbLNqL2bI0rZXqby9/LBiKSxNH/czrvLTsKCmVUtO7r8A34QZZRIxixQCxMg4N1N25FBHY9lygjC6cK7M2PFiruBm3Xt0O727QtUZYeYJ5dE3qimj03Uv8oh1O6MGwNmmND4MXsuqB9zCs3JUvrUz5Xm6TucVCIYkYPiYIuwJGE4PJSxCN5VdgjaFECMcVd8ejSlvDrQ7Icp9Ej8QSQdEcXaZIYtn7epx+FC8cOWFSekRJD/pJn+yj4JwU0+ZrvqZv8Hp71EzhmGWg3e7Q5qTkYHiMSFQywd+iKY8Gp4yJCM48ekvkMzjJHx1M+ODTUau5fFjG/9ypOzLNmxxe4ZMAt/oT69GHTmNIyMYHpOeYllTU/1vGOFmFZ7N4wpl/Max+HTHY8tI4L481BrPEoUmryPhYUDuQVygtKhxJDtqNthEUzehlw552pCcpAPSmI44w+GR2YIeQxQyUM+CiJZiJZhpaZ9x91fnFZ2nz6CVGKZwdanNzM/V48ZROeNCiSOb7fs+akr8KAxwbM5Tys4++LCNb19i2EHOZn3/pUExNqjCEXMFVSGYUjogo4=
  skip_cleanup: true
  file_glob: true
  file:
  - "dist/oem-database-updater-anidb-*"
  - "dist/oem_database_updater_anidb-*"
  on:
    repo: OpenEntityMap/oem-database-updater-anidb
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
    tags: true
